GET http://localhost:3003/usuario?nome=gabriel
Content-Type: application/json

###

GET http://localhost:3003/usuario/305176b0-7a40-4662-977c-6a03ae30d697
Content-Type: application/json

###

POST http://localhost:3003/usuario
Content-Type: application/json

{
    "email": "gabrielpereira@gmail.com",
    "primeiro_nome": "Gabriel",
    "ultimo_nome": "Pereira",
    "telefone": "5521995116053",
    "password": "gabrielpereira"
}

###

PUT http://localhost:3003/usuario/305176b0-7a40-4662-977c-6a03ae30d697
Content-Type: application/json

{
    "email": "gabrielgomes@gmail.com",
    "primeiro_nome": "Gabriel",
    "ultimo_nome": "Gomes",
    "telefone": "5521995116054",
    "senha": "gabrielgomes"
}