GET http://localhost:3003/usuario
Content-Type: application/json

###

GET http://localhost:3003/usuario/dd5d1570-d098-4bc6-9b61-4ee60bac5e3b
Content-Type: application/json

###

POST http://localhost:3003/usuario
Content-Type: application/json

{
    "email": "athenaambrozino@gmail.com",
    "primeiro_nome": "Athena",
    "ultimo_nome": "Ambrozino",
    "telefone": "5521995116053",
    "password": "athenaambrozino"
}